# Generated by Django 4.0.1 on 2022-01-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.IntegerField(choices=[(0, 'DOCTORATE'), (1, 'MASTER DEGREE'), (2, 'BECHALOR DEGREE'), (3, 'DIPLOMA IN'), (4, 'ASSOCIATE DEGREE'), (5, 'HIGH SCHOOL')]),
        ),
    ]
