# Generated by Django 4.0.1 on 2022-01-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_education_end_date_month_education_end_date_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.IntegerField(choices=[(0, 'DOCTORATE'), (1, 'MASTER DEGREE'), (2, 'BACHELOR DEGREE'), (3, 'DIPLOMA IN'), (4, 'ASSOCIATE DEGREE'), (5, 'HIGH SCHOOL')]),
        ),
    ]
