# Generated by Django 4.0.1 on 2022-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('entry', models.CharField(max_length=130)),
                ('body', models.TextField()),
                ('publish_date', models.DateField()),
                ('category', models.IntegerField(choices=[(1, 'Django')], default=1)),
                ('img', models.ImageField(upload_to='blog/')),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
    ]
