# Generated by Django 4.0.1 on 2022-01-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(null=True, upload_to='blog/'),
        ),
    ]
