# Generated by Django 4.0.1 on 2022-02-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('entry', models.CharField(max_length=130)),
                ('body', models.TextField()),
                ('publish_date', models.DateField()),
                ('category', models.IntegerField(choices=[(1, 'Django')], default=1)),
                ('img', models.ImageField(blank=True, null=True, upload_to='works/')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Work',
            },
        ),
    ]
